### ISSUE TITLE
Support for jpeg2000 format

### ISSUE THREAD

**Issue by nattomi** [markummitchell/engauge6#1]
Hi! On my platform QImageReader::supportedImageFormats() returns the following formats: *.bmp *.gif *.ico *.jpeg *.jpg *.pbm *.pgm *.png *.ppm *.svg *.svgz *.xbm *.xpm. Would it be possible to extend this list with the JPEG 2000 format (see http://en.wikipedia.org/wiki/JPEG_2000)? There is a class called QtJP2ImageFormat (http://doc.qt.digia.com/solutions/3/qtjp2imageformat/qtjp2imageformat.html) but as I'm not experienced in Qt I had no luck with integrating it into ED so far.

**Comment by nattomi** [comment]
Hi Mark! Thank you for your answer! I guess @grizleys1 can also answer here as well, so other people can read it. We intend to work with thousands of images and inserting an extra conversion step (using f.i. ImageMagick) just makes everything slower. There is a reason why jp2 has been preferred in contrast to jpg but I do not want to go into details here. Anyways, this is not really an Engauge-specific question then, so I'd better ask this on the Qt forums.

**Comment by markummitchell** [comment]
Just found a possible solution to add JPEG2000 support. The OpenJPEG project creates a self-contained library. Calling that library only takes about 200 lines of custom code.

That library builds with cmake. 

Maybe code to call OpenJPEG could be added as an option. There is also the possibility of creating a plugin.

**Comment by nattomi** [comment]
Thank you for the info! Momentarily I'm too busy to make any contribution but I might come back to this problem at a later time. It would be nice to have this, but it's not an urgent issue.

**Comment by markummitchell** [comment]
Implemented using OpenJPEG library.
