### ISSUE TITLE
Help window empty

### ISSUE THREAD

**Issue by sagitter** [markummitchell/engauge6#11]
Hi all,

The window from ```Help --> Help (F1)``` is empty.

Screenshot: (http://postimg.org/image/wkbyzhayd/)

This is the output from terminal:

```$ engauge
QTextBrowser: No document for qthelp://engaugedigitizer.net/doc/index.html```

Thanks.

**Comment by markummitchell** [comment]
Hello. Immediate fix for the help file is to run help/build script. I've also created an INSTALL documentation file that will hopefully be helpful for other trying to build the software.

**Comment by sagitter** [comment]
HI @markummitchell,

what i meant is that if i install ```engauge``` in a system's directory tree (those of Fedora in this case) , i can't put documentation ```.qhc``` file under ```/usr/bin/documentation```; indeed, ```engauge``` search HELP file just there if packaged and installed:

```
stat("/usr/bin/documentation/engauge.qhc", 0x7ffc2e165390) = -1 ENOENT (No such file or directory)
open("/usr/bin/documentation/engauge.qhc", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = -1 ENOENT (No such file or directory)
open("/usr/bin/documentation/engauge.qhc", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

How can i change default HELP files directory (e.g. ```/usr/share/doc/engauge```)?

Thanks.

**Comment by sagitter** [comment]
I have temporarily resolved with this patch:

```
--- src/Help/HelpWindow.orig.cpp	2015-09-28 04:36:59.000000000 +0200
+++ src/Help/HelpWindow.cpp	2015-09-28 15:01:45.483084067 +0200
@@ -17,7 +17,7 @@
   setMinimumWidth (MIN_WIDTH);
   setMinimumHeight (MIN_HEIGHT);
 
-  QString path = QApplication::applicationDirPath() + "/documentation/engauge.qhc";
+  QString path = QApplication::applicationDirPath() + "/../share/doc/engauge-digitizer/engauge.qhc";
   QHelpEngine *helpEngine = new QHelpEngine (path);
   helpEngine->setupData();
 
 ```

**Comment by markummitchell** [comment]
A reasonable number of alternative paths can be inserted into HelpWindow.cpp, and the code will search through those until it finds the help file. This approach was selected instead of the use of an environment variable.
