### ISSUE TITLE
static build for windows

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge6#19]
Hi,
With the old version 5.1 of engauge digitizer I was able to build the static app for Windows.
Now, current version of engauge6 built against Qt 5.5 gives some link errors if I try to link statically. I don't know whether it is a valuable target, but having static version would be good. If I succeed building one, I will share it.

See, I built it on Linux with the help of mingw
http://copr.fedoraproject.org/coprs/baurzhanm/mingw64-engauge-digitizer/build/33070

**Comment by markummitchell** [comment]
Hi Baurzhan,
Supporting both static and dynamic builds would be very nice.

I just realized that I had not already added you as a collaborator. You are
now a collaborator, if you want to make any changes directly. Or you can
make changes on your own fork.

I will look at your build 33070 link this evening.

Thanks for your help
Mark Mitchell

**Comment by markummitchell** [comment]
It seems that the Help Collection offered by Qt only works when linking dynamically. I would like to include the Help, so I will initially release a dynamically-linked Linux version using a wrapper script to set LD_LIBRARY_PATH. Maybe that would be sufficient for everyone.

**Comment by crayxt** [comment]
Could you point me to a info of Help linkage, is it applicable to Linux only?
Sure for Linux statically linked app is not appropriate. I only wanted static app for Windows for convenience (and because older version of Engauge worked as a static app).

**Comment by markummitchell** [comment]
In a fresh linux build for dynamic linking, the qcollectiongenerator,
qhelpconvert and qhelpgenerator executables were created (which build help
files). Also, the libQtHelp library was built.

In a fresh linux build for static linking, those same binary and library
files were not created.

I could not find any official documentation on Qt Help and static linking.

Have you tried the Windows installer, on Sourceforge?

**Comment by crayxt** [comment]
Ok, no rush for static builds.
Just tried installed from sourceforge for Engauge 6.0, 
1) it seems like you forgot to include Qt platform plugin windows, it must reside in platforms folder in next to engauge.exe file (file qwindows.exe). 
2) Also I see no folder with imageformats plugins. 
3) And it looks like you are providing debug build, judging by size of 62 MB of engauge.exe
4) Installer terminated with no final message, I expected to see some kind of Success message. Is this installer better than NSIS?

**Comment by markummitchell** [comment]
There is a much better installer for Engauge 6.0 at sourceforge. I don't
build with WIndows often, so the process took some time.

**Comment by jkulesza** [comment]
@markummitchell, have you considered using the [Releases(https://github.com/blog/1547-release-your-software) feature on Github for managing the installer?  

This might allow some centralization of the project.  My understanding is also that SourceForge has been found doing some 'funny business' lately and might let you move away from them if you object to those claims.

**Comment by markummitchell** [comment]
Is there an advantage to using Github Releases over the WiX for Windows and makeself for Linux? I've made the WiX installation package much more robust with additional bells and whistles. The makeself installer also works nicely. Moving to a new installer would mean a lot of work. Also, regarding Sourceforge and Github, the consensus seems to be to move to github, if for no other reason than the Sourceforge issue with "enhanced" installers and confusion that has caused.

**Comment by crayxt** [comment]
I never personally released anything or dealt with installers, cannot help here.
BTW, regarding Linux installer, in which distribution have you prepared it? it didn't work for me due to library versioning errors, in Fedora 23 64-bit. Luckily Fedora has latest version in its repos already.

**Comment by crayxt** [comment]
Now I am not able to uninstall version from Sourceforge, any advice?

**Comment by jkulesza** [comment]
@markummitchell, my understanding of Github Releases is that it is primarily a method to distribute whatever type of installer(s) you create, through whatever method you choose.  It also has the advantage of tying them to one of the commits in the code so the code base is tied to particular installer(s).

Regarding the consensus of moving to Github from SourceForge --- that too has been my observation.

**Comment by crayxt** [comment]
Nope, uninstall worked, sorry. Had to right click on original MSI file and select "Uninstall"

**Comment by markummitchell** [comment]
Thanks everybody for the help. I learned about github releases and other nice tools. Regarding the original issue's description regarding 'static Windows builds' - I would like to stay with dynamic builds. They seem to get the job done (especially when the WiX installer is used), do not require lengthy Qt static rebuilds, and accommodate plugins (especially the Help and Jpeg2000 modules).
