### ISSUE TITLE
why windows release file called 64-bit

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge6#27]
Actually, why? The files inside are 32-bit ones, calling the archive 64-bit may cause wrong impression for users.

**Comment by markummitchell** [comment]
My mistake. I build on a 64 bit operating system, and assumed the release
would not work on a 32 bit operating system. If you can verify that is
true, I would like to make a new release with the fixes since 6.0.

**Comment by crayxt** [comment]
Actually I don't have 32 bit windows around to test that.

**Comment by markummitchell** [comment]
I will try to run with WINE in 32 bit mode.

**Comment by crayxt** [comment]
I think it is time for minor release

**Comment by crayxt** [comment]
Ok, I see the new release. Works fine.
