### ISSUE TITLE
windows release: ability to install without admin privileges

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge6#28]
For some users, installing MSI might be an issue, since it requires administrator privileges.
It would be good to have an ability for installing to user specified directory.

**Comment by markummitchell** [comment]
The Windows installer now lets the user specify an installation directory.
I tried it out at one point and that worked.

**Comment by crayxt** [comment]
Ok I see the new release. Unfortunately, one should uninstall previous version before being able to install this one. While I can point it to custom installation directory, admin privileges are still required.
BTW what happened to desktop icon, why is it almost transparent?

**Comment by markummitchell** [comment]
The Windows release build process now also builds a zip file that contains exactly the same files that get installed when using the msi installer. Testing on a Windows 7 system worked fine, after unzipping.

The icons were broken for version 6.1 - specifically the centers were transparent. They have been fixed for 6.2.

**Comment by markummitchell** [comment]
Zip file is now created as part of the release build process, for Windows.
