### ISSUE TITLE
Settings -> Curve properties, Preview area is stretched horizontally

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge6#29]
Just noticed that preview area of Curve properties is too stretched horizontally, thus axes/curves marks look compressed on preview area.

**Comment by crayxt** [comment]
Just saw, the Settings -> Curve properties window can be resized vertically. In this case, we need smaller preview area with correct side ratios (not stretched).

**Comment by markummitchell** [comment]
Fixed in version 6.2
