### ISSUE TITLE
Feature Request: Zoomed picture-in-picture

### ISSUE THREAD

**Issue by LiaungYip** [markummitchell/engauge6#3]
It would be helpful if the new version of Engauge supported a zoomed in 'picture in picture' view which follows the cursor. This would make it easier to precisely locate points on the image, without having to zoom in the entire view.

[WebPlotDigitizer](http://arohatgi.info/WebPlotDigitizer/app/?) implements this feature, for example.

![image](https://cloud.githubusercontent.com/assets/2173684/5736677/b1657e02-9c13-11e4-88d0-cdc6390bbb5e.png)

**Comment by grizleys1** [comment]
LiaungYip, 
This feature may be useful, or may not be needed because a much improved system of zooming is used - which is adjustable by keyboard like GIMP or by resizing the main window. For now, let's keep this. Thank you!

**Comment by markummitchell** [comment]
Current approach is simpler (especially if user realizes that resizing the main window 'resets' the zoom factor while in Fill mode).
