### ISSUE TITLE
On File-Close, reset the Engauge state, deactivate axes and curves buttons

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge6#33]
After you close an image/dig file, the axes and curves buttons on main panel remain active, pressing axes button causes Engauge being terminated by Windows. You need to reset Engauge state, so buttons are inactive when image/dig file is closed.

**Comment by crayxt** [comment]
Actually all settings are available, calling any of them triggers Engauge's termination.

**Comment by markummitchell** [comment]
Fixed in version 6.2
