### ISSUE TITLE
Support drag and drop of image/DIG files onto engauge.exe

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge6#34]
Just a usability feature - current version 6.1 in Windows does nothing, if you drag and drop image of dig file onto engauge.exe

**Comment by markummitchell** [comment]
Fixed in version 6.2

**Comment by crayxt** [comment]
I meant, when Engauge is not open, if you drag and drop a file on top of engauge.exe, nothing happens.

**Comment by markummitchell** [comment]
File names specified in the command line get automatically loaded at startup. One instance of Engauge will be created for each specified file. The files can either be DIG files (which get opened) or image files (which get imported).

**Comment by k1moradi** [comment]
Dragging and dropping a PNG file does not do anything. I think the program should import the png file.

**Comment by markummitchell** [comment]
The last post is now issue #331
