### ISSUE TITLE
Make File-Save work on fresh project

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge6#35]
Pulling from https://github.com/markummitchell/engauge6/issues/24

On Freshly created project, in File menu, Save is inactive, and Save as is active. On in-memory projects, which are not saved yet, I think that File-Save must work as File-Save as.

**Comment by markummitchell** [comment]
Save is now available when Save As is available after import

**Comment by crayxt** [comment]
I don't understand. After import Save As is available, but Save - not.

**Comment by markummitchell** [comment]
Looks like I need to make sure changes are pushed to github immediately or else these comments are confusing because they describe changes that are not yet shared.

**Comment by markummitchell** [comment]
Fixed in version 6.2
