### ISSUE TITLE
MSI releases not upgradeable

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge6#37]
I tried to install 6.2 in MSI, and it says that Another version of this product is already installed, pointing to 6.1 release I have installed. Same was with the previous 6.1 release. Are MSI's able to do upgrade over previous version?

**Comment by markummitchell** [comment]
The build process now provides for upgrades with MSI installations. However, upgrading from versions 6.0 or 6.1 will still require manually uninstalling first - since both old and new versions do special magic behind the scenes to make this work. Versions 6.2 and on now support MSI upgrades.
