### ISSUE TITLE
Feature Request: Automatically recognise 'dominant colours' for easy digitisation of coloured curves

### ISSUE THREAD

**Issue by LiaungYip** [markummitchell/engauge6#4]
It would be useful if the new version of Engauge was able to recognise the dominant colours in an image, and automatically digitise curves of a given colour.

This is a feature implemented by WebPlotDigitizer. In the example screenshot below, I have told WebPlotDigitizer that I would like to digitize the blue curve. WebPlotDigitizer also auto-detects that the dominant colours in this image are red, yellow, green, and blue, with an easy way of selecting these colours.

![image](https://cloud.githubusercontent.com/assets/2173684/5736753/8e0953ba-9c14-11e4-9008-18dbad199e9c.png)

**Comment by grizleys1** [comment]
LiaungYip, 
This feature will be implemented. Thank you!

**Comment by markummitchell** [comment]
Color Picker tool selects the color filtering for the current curve. Also, the toolbar shows the current color filtering
