### ISSUE TITLE
Build fails on Ubuntu 14.04 relating to libQt5Help

### ISSUE THREAD

**Issue by sebjameswml** [markummitchell/engauge6#43]
Hello,

I find the code won't build on Ubuntu 14.04:

[seb@PSY0001622 11:24:25 engauge6]$ qmake engauge.pro
Project MESSAGE: Building debug version without internal support for JPEG2000 files
Project ERROR: Unknown module(s) in QT: help

I do have libqt5help installed:

[seb@PSY0001622 11:42:21 engauge6]$ aptitude search qt5 | grep help
i A libqt5help5                     - Qt 5 help module                          
p   libqt5help5:i386                - Qt 5 help module                          
[seb@PSY0001622 11:43:57 engauge6]$ 

This problem didn't occur when I built on Debian 8. One difference is that I have a version of Qt installed in my home directory on the Debian system and I don't on the Ubuntu 14.04 system.

**Comment by nattomi** [comment]
Hi @sebjameswml,

I experienced the same problem. I believe installing `qttools5-dev` which made me overcome this error. Could you give it a try?

**Comment by TobiasWinchen** [comment]
Hi,

On Monday 07 December 2015 03:59:54 Tamás Nagy wrote:

> I experienced the same problem. I believe installing `qttools5-dev` which
> made me overcome this error. Could you give it a try?

I am currently preparing .deb packages for the inclusion in Debian and Ubuntu. 
The build depends you need are:

Build-Depends: dpkg-dev (>= 1.16.1~), debhelper (>= 9), qtbase5-dev, qtbase5-
dev-tools, qttools5-dev, qttools5-dev-tools, libqt5sql5-sqlite, libfftw3-dev, 
libpng12-dev, libjpeg-dev, liblog4cpp5-dev

In a mixed Qt4 and Qt5 environment you need to make sure that the environment 
points to the correct location by using qtchooser and or the environment 
variable QT_SELECT=qt5

Best regards,


Tobi

**Comment by sebjameswml** [comment]
Hi @nattomi & @TobiasWinchen 

That's great - I was missing qttools5-dev and qttools5-dev-tools from the installed components. Would be worth adding those to the list of dependencies in the INSTALL file.

**Comment by markummitchell** [comment]
HI Tobias, Are dpkg-dev, debhelper and libqt5sql5-sqlite needed for builds that will not be distributed as Debian/Ubuntu packages?

**Comment by nattomi** [comment]
Hi Tobias, it's kinda offtopic here, but would you be so kind to incorporate jpeg2000 support into the .deb package as well? See https://github.com/uclouvain/openjpeg/issues/616 about possible complications.
