### ISSUE TITLE
Crash in 'Export Settings Dialog' when multiple curves are defined but only one has data points

### ISSUE THREAD

**Issue by TobiasWinchen** [markummitchell/engauge6#46]
Steps to reproduce:
* Import new file
* Add Multiple Curves
* Add Axes: Opening Export Settings works as expected
* Add points to first curve:Opening Export Settings crashes with 
     `terminate called after throwing an instance of 'std::bad_alloc'
     what():  std::bad_alloc`

The dialog doesn't crash if all curves have data points. 
Engauge version is 6.2.

**Comment by markummitchell** [comment]
Excellent information. Should be easy to find.
