### ISSUE TITLE
Zoom In/Out With Ctrl+MouseWheel

### ISSUE THREAD

**Issue by TobiasWinchen** [markummitchell/engauge6#47]
Would be a nice feature as this behavior is default in several other applications

**Comment by markummitchell** [comment]
For issue #25, the default zoom factor was changed from Fill to 1:1. However, the last checkin lets the user change the default zoom factor. @TobiasWinchen - what do  you think of having the default as Fill? Users who prefer 1:1 can select it now as the default.
