### ISSUE TITLE
logo conversion to svg

### ISSUE THREAD

**Issue by keszybz** [markummitchell/engauge6#5]
Hi,
as preparation for Fedora package, I convert the original digitizer logo to SVG (existing icon is too small for HiDPI environments). It is at http://in.waw.pl/~zbyszek/fedora/engauge-digitizer.svg .
There's also a version with the "engauge" name, but since desktops tend to include the application name under the icon anyway, it is less useful:  http://in.waw.pl/~zbyszek/fedora/engauge-digitizer-with-name.svg . Would be great if you could add this icon as default or alternative.

**Comment by grizleys1** [comment]
The svg file has been added to the old Engauge over at sourceforge.net. The main window's icon is set to the svg file if the QtSvg package is loaded, otherwise the old icon is used. If this looks good, the code will be copied to engauge6 at github. Thanks!
