### ISSUE TITLE
Comma as decimal point not handled correctly

### ISSUE THREAD

**Issue by VegarS** [markummitchell/engauge6#51]
Certain locales (e.g. Norwegian, German) use comma as the decimal separator (1.23 is written as 1,23). This is not handled correctly by the axis point tool, the string 1,23 is converted to 1.0.

As the validator for the lineedits in the axis point dialog recognises that my locale's decimal point is comma, I am not allowed to manually enter a dot instead, severly limiting the usability of the tool.

It seems QString::toDouble is always using the C locale since Qt5, so the fix is to use QLocale::toDouble instead of QString::toDouble. 

I fixed this for the axis point tool (at least for cartesian coordinates) by editing src/Format/FormatCoordsUnitsStrategyNonPolarTheta.cpp, in FormatCoordsUnitsStrategyNonPolarTheta::formattedToUnformatted(), on line 42:

`value = string.toDouble ();`
should be replaced by
`value = QLocale::system().toDouble(string);`

This is a potential issue elsewhere in the program as well, especially where user input is handled.

**Comment by markummitchell** [comment]
Thanks for the request. I had always thought it would be good to add this feature, but did not feel qualified to test it since I am only familiar with my locale.The Main Window settings now offer a locale option. Please feel free to try it.
