### ISSUE TITLE
Feature Request: Portable version

### ISSUE THREAD

**Issue by orestesgaolin** [markummitchell/engauge6#52]
Hi, would it be possible to publish a portable (Windows) version of the Engauge6?

**Comment by markummitchell** [comment]
I am wondering if by "portable" you mean "mobile"? If so, would you suggest a specific device? Before adding support, I would like to make sure the hardware is good enough. Specifically, the screen resolution should be good enough, and I haven't looked at mobile devices lately.

**Comment by orestesgaolin** [comment]
What I mean is the version which is for example one .exe file and some small configuration file that doesn't need to be installed. Such portable version could be run from a USB flash disk on a library computer etc.

**Comment by markummitchell** [comment]
That makes sense. I will work on it.

**Comment by orestesgaolin** [comment]
Thank you very much, that would be very useful :)

**Comment by crayxt** [comment]
We already have ZIP version, which does not require installation. Have you tried it?

**Comment by orestesgaolin** [comment]
@crayxt Could you help me to locate it? I'm a bit newbie and cannot find this .zip package.

**Comment by crayxt** [comment]
@orestesgaolin See the Releases tab https://github.com/markummitchell/engauge6/releases

The latest ZIP file https://github.com/markummitchell/engauge6/releases/download/v6.2/digit-exe-windows-32-bit-zip-file-6_2.zip

**Comment by orestesgaolin** [comment]
@crayxt Thank you, it works flawlessly :)

**Comment by crayxt** [comment]
@orestesgaolin If you ok with this solution, you may want to close this ticket, thanks
