### ISSUE TITLE
Feature: More detailed installation instruction for Windows 10 / 64bit?

### ISSUE THREAD

**Issue by MarkusEmm** [markummitchell/engauge6#54]
Hey there!

I am a huge fan of the older version of engauge, but right now I am having performance issues.
I wanted to upgrade to the newest version and can't seem to make the software compile.
Why not provide a standalone-installer?

If there is any help, it would be greatly appreciated!
Steps I did so far:
1) Read INSTALL file
2) Install QT toolkit : http://ftp.fau.de/qtproject/archive/qt/5.5/5.5.1/qt-opensource-windows-x86-mingw492-5.5.1.exe

3) Download precompiled fftw, registered path FFTW_HOME
4) Download and build log4cpp: Download works, build not so much. I applied steps 2a-d as suggested, however, time(X) couldn't be found in the code.
So... I put everything in C:\log4cpp\ and started the shell QT55 (MinGW 4.9.2. 32-bit) and tried the "./configure , make and make install command" - ./configure was not recognized.

Do I need to enter it in another, specific way?

Also, I installed some CMake package for QT, as a cmake-file was available in log4cpp, but when I try to build from QT GUI it wants me to specify an executable..

Sorry if I miss on something obvious...

**Comment by crayxt** [comment]
Hi, why not use the pre-compiled version provided here in Releases?
https://github.com/markummitchell/engauge6/releases

**Comment by MarkusEmm** [comment]
Alright.. obviously I'm too dumb to navigate github ^^

Thanks!

**Comment by markummitchell** [comment]
MarkusEmm, the documentation did need some improvement. I've added some information to save other who would have been confused also. Thanks
