### ISSUE TITLE
CI integration

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge6#57]
I think attaching this project to some CI (like travis) could help identifying issues like https://github.com/markummitchell/engauge6/issues/56

**Comment by markummitchell** [comment]
The build_and_run_all_tests script can be used to run some low-level tests, using the Qt test framework. The existing tests do not exercise the gui.

I am thinking of adding some high-level tests that actually bring up the gui and run through the steps that users would follow in various situations. I could not determine if travis could do that.

**Comment by crayxt** [comment]
I meant more like compiling pull requests with different compilers to catch errors early.

**Comment by markummitchell** [comment]
That sounds like a good idea. Are you familiar with setting that up?

**Comment by crayxt** [comment]
Just a little. I will configure it in a forked project, then suggest as PR.

**Comment by markummitchell** [comment]
This could be useful for pre-checking upcoming Version 7. I've also created build_and_run_all_cli_tests and build_and_run_all_gui_tests scripts for regression testing.

**Comment by crayxt** [comment]
@markummitchell 
I have prepared simple configuration file https://github.com/markummitchell/engauge6/pull/60 so you need it merged first.
You can register on Travis with your github account and enable builds for PRs, then you need to merge a PR only when its build succeeds.

**Comment by crayxt** [comment]
by the way, travis uses ubuntu 14.04 so we are on Qt 5.2.1

**Comment by markummitchell** [comment]
Thanks Baurzhan for setting up the process. Travis is a very useful tool. There are a couple of differences in the regression tests between expected and actual results that I will look into later, but the process is working nicely.

**Comment by crayxt** [comment]
Glad it worked. I just added status badge to README.
