### ISSUE TITLE
Make fails on Ubuntu

### ISSUE THREAD

**Issue by iancrossfield** [markummitchell/engauge6#59]
Running qmake seems to work OK, though two warnings occur:
> Project MESSAGE: Building debug version without internal support for JPEG2000 files
> Project MESSAGE: Warning: unknown QT: help

But running make on the generated Makefile yields only errors:

> make
g++ -c -pipe -g -D_REENTRANT -Wall -W -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../anaconda2/mkspecs/linux-g++ -I. -I../../anaconda2/include/QtCore -I../../anaconda2/include/QtNetwork -I../../anaconda2/include/QtGui -I../../anaconda2/include/QtXml -I../../anaconda2/include -Isrc -Isrc/Background -Isrc/Callback -Isrc/Checker -Isrc/Checklist -Isrc/Cmd -Isrc/Color -Isrc/Coord -Isrc/Correlation -Isrc/Cursor -Isrc/Curve -Isrc/DigitizeState -Isrc/Dlg -Isrc/Document -Isrc/Export -Isrc/Filter -Isrc/Format -Isrc/Graphics -Isrc/Grid -Isrc/Help -Isrc/img -Isrc/include -Isrc/Line -Isrc/Load -Isrc/Logger -Isrc/main -Isrc/Mime -Isrc/Network -Isrc/Ordinal -Isrc/Plot -Isrc/Point -Isrc/Segment -Isrc/Settings -Isrc/Spline -Isrc/StatusBar -Isrc/Transformation -Isrc/Tutorial -Isrc/util -Isrc/View -Isrc/Zoom -Isrc/.moc -o src/.objs/BackgroundImage.o src/Background/BackgroundImage.cpp
g++ -c -pipe -g -D_REENTRANT -Wall -W -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../anaconda2/mkspecs/linux-g++ -I. -I../../anaconda2/include/QtCore -I../../anaconda2/include/QtNetwork -I../../anaconda2/include/QtGui -I../../anaconda2/include/QtXml -I../../anaconda2/include -Isrc -Isrc/Background -Isrc/Callback -Isrc/Checker -Isrc/Checklist -Isrc/Cmd -Isrc/Color -Isrc/Coord -Isrc/Correlation -Isrc/Cursor -Isrc/Curve -Isrc/DigitizeState -Isrc/Dlg -Isrc/Document -Isrc/Export -Isrc/Filter -Isrc/Format -Isrc/Graphics -Isrc/Grid -Isrc/Help -Isrc/img -Isrc/include -Isrc/Line -Isrc/Load -Isrc/Logger -Isrc/main -Isrc/Mime -Isrc/Network -Isrc/Ordinal -Isrc/Plot -Isrc/Point -Isrc/Segment -Isrc/Settings -Isrc/Spline -Isrc/StatusBar -Isrc/Transformation -Isrc/Tutorial -Isrc/util -Isrc/View -Isrc/Zoom -Isrc/.moc -o src/.objs/BackgroundStateAbstractBase.o src/Background/BackgroundStateAbstractBase.cpp
In file included from src/include/EngaugeAssert.h:4:0,
                 from src/Background/BackgroundStateAbstractBase.cpp:3:
src/Logger/LoggerUpload.h:28:36: error: expected ‘;’ at end of member declaration
                            int line) NO_RETURN_VALUE;
                                    ^
src/Logger/LoggerUpload.h:9:25: error: ‘Q_NORETURN’ does not name a type
 #define NO_RETURN_VALUE Q_NORETURN
                         ^
src/Logger/LoggerUpload.h:28:38: note: in expansion of macro ‘NO_RETURN_VALUE’
                            int line) NO_RETURN_VALUE;
                                      ^
src/Logger/LoggerUpload.h:33:39: error: expected ‘;’ at end of member declaration
                               int line) NO_RETURN_VALUE;
                                       ^
src/Logger/LoggerUpload.h:9:25: error: ‘Q_NORETURN’ does not name a type
 #define NO_RETURN_VALUE Q_NORETURN

**Comment by markummitchell** [comment]
I would like to try to reproduce this problem so I can fix it. It would be helpful if you can say which version of Ubuntu you are using, and if the operating system uses 32 bits or 64 bits. Also, what is the output of 'g++    -v'?

**Comment by crayxt** [comment]
Is it qmake from Qt5? You may want to uninstall qt4 dev packages

**Comment by markummitchell** [comment]
Running 'qmake -v' will give the qmake version

**Comment by iancrossfield** [comment]
I'm running Ubuntu 14.04 LTS, 64 bit.  

> g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) 

> qmake -v
QMake version 2.01a
Using Qt version 4.8.7 in /home/ianc/anaconda2/lib

If I need to install qt5, which of the many qt5-related packages are recommended?

**Comment by markummitchell** [comment]
I think the problem is in the 'qmake -v' output. Your qmake is set for qt4.8.7. Hopefully switching to qt5, which is required, will also fix your compilation problem. The INSTALL file in the main directory has a list of packages that are probably required, if you are building Engauge yourself. 

Can you use a pre-built package? That can save a lot of time. We recently upgraded the documentation so everyone would know that there are pre-built Engauge packages at https://github.com/markummitchell/engauge6/releases. Also, Ubuntu has in its repository an Engauge package (thanks to the excellent package maintainers).

**Comment by iancrossfield** [comment]
Ha! Thanks, this does the trick:
> sudo apt-get install engauge-digitizer

Someone might add a line to the "INSTALL" notes, to suggest this as an alternative option.
