### ISSUE TITLE
appdata file

### ISSUE THREAD

**Issue by keszybz** [markummitchell/engauge6#6]
Hi,
I'm working on adding an appdata file (http://people.freedesktop.org/~hughsient/appdata/) to have engauge (the old version) displayed in Gnome Software installer. Please consider adding this file. It should be installed into /usr/share/appdata/engauge-digitizer.appdata.xml on a Linux system.
The description is based on the text on engauge website, but the screenshots were made to me. The screenshots are rather bad, but Gnome Software wants screenshots in 16:9 ratio and fairly high resolution, so the screeshots on the website didn't fit well. There's one screenshot that I made and the two from the website, which are more interesting, but don't pass the minimum resolution test for Gnome Software. File is at http://in.waw.pl/~zbyszek/fedora/engauge-digitizer.appdata.xml .

**Comment by grizleys1** [comment]
The appdata file has been added to the old Engauge over at sourceforge.net, in the new gnome directory. We changed that file to load the three images from digitizer.sourceforge.net/gnome instead of your personal directory. Thanks!

**Comment by markummitchell** [comment]
Added to version 6.

**Comment by sagitter** [comment]
The links to the screenshots do not work: https://github.com/markummitchell/engauge6/blob/master/gnome/engauge-digitizer.appdata.xml

**Comment by keszybz** [comment]
The pull request fixes things for now, but it would be great to redo the screenshots on the new version of course.
