### ISSUE TITLE
Paste as New

### ISSUE THREAD

**Issue by alexsconway** [markummitchell/engauge6#62]
Pretty much the only way I use Engague 4.1 is by taking a snapshot of a graph in a pdf (eg a power transistor datasheet) and selecting Edit>Paste as New. Could we please have that in V6.x.
Thanks,
Alex

**Comment by markummitchell** [comment]
Sounds like a good idea

**Comment by markummitchell** [comment]
This should be working in the unreleased code, if you want to try it out.

**Comment by crayxt** [comment]
@markummitchell I tried it and can confirm it works. However, same issue as https://github.com/markummitchell/engauge6/issues/66 applies.

**Comment by alexsconway** [comment]
I'll have to take your words on it. I have tried building on wiindows but, not having much experience in getting such a build environment to work, I'ts not working. I could probably get there after a day or two but I'd like to keep my hair.
Much as I'd love to ditch windows, I can't due to large amounts of engineering stuff which wants windows. I'm still on XP, aargh.

**Comment by markummitchell** [comment]
I feel your pain. The good news is that I am aiming to come out with a new release in the next week or two. It will support Windows and Linux. For any Mac users out there, I am working on Mac support also.
