### ISSUE TITLE
Documentation Suggestion: Convert OpenDocument Files to LaTeX / LyX

### ISSUE THREAD

**Issue by jkulesza** [markummitchell/engauge6#7]
I would propose converting your user (and programmer) documentation from open document formats to LaTeX.  To permit ease-of-editing, I would propose using LyX as a front-end for maintaining this documentation.  

This will permit broader consumption capability (requiring a PDF viewer) and will also permit granular change tracking through Github (currently not available for the documents).

I'd be willing to lend a hand in getting this conversion going if Mark agrees.

**Comment by jkulesza** [comment]
My apologies, I was looking in the /doc directory and saw the Open Document formats but then after looking more I saw the Doxygen materials which satisfies my concern.  Please disregard this.

**Comment by markummitchell** [comment]
Thanks for the input anyway. Always good to know what does and does not work for everyone. Thanks
