### ISSUE TITLE
JP2 from Qt plugins - how good is it?

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge6#74]
I personally have no JP2 files to test. In list of Qt plugins I see jp2 plugin - is it the same functionality that openjp2 provides? Should I link jpeg2000 to CI tests?

**Comment by markummitchell** [comment]
There is a jpeg2000.jp2 file in the samples directory. Regarding the jp2 Qt plugin - if that is available then it is preferred over the openjp2 code (which was a temporary solution until Qt supported JPEG2000).  Your call on the CI tests.

**Comment by crayxt** [comment]
It opens in recent appveyor build. So I will not evaluate it further. Thanks,
