### ISSUE TITLE
The "Axis Point Tool" wont accept decimal numbers except in exponent format

### ISSUE THREAD

**Issue by np-8** [markummitchell/engauge6#75]
Hello,

I am trying to digitize a graph similar to [this](http://www.tvu.com/PNextGenTFwebFig3.jpg). However, the Axis point tool won't accept any decimal numbers, except in the 'e' format.
- Dot cannot be inserted (nothing happens when pressing dot on keyboard)
- Comma in any decimal number turns the number to be zero.
- The tool _will accept 2e-1_, which will be translated into "0.2" after pressing Ok. However, when trying to edit the point, the dot notation must be replaced with the 'e'-notation.

![bug](https://cloud.githubusercontent.com/assets/17479683/13327775/e985418e-dbf3-11e5-9132-a2403d54f860.PNG)

**Comment by crayxt** [comment]
What is your system locale?

**Comment by crayxt** [comment]
And Engauge version, please

**Comment by np-8** [comment]
Using [this](http://windows.microsoft.com/en-us/windows/change-system-locale#1TC=windows-7) definition for system locale, it is "Finnish (Finland)". Engauge version 6.2. Tried both the .exe from the .zip and the .msi installer. I am using Windows 7.

**Comment by crayxt** [comment]
@np-8 there are some improvements in upcoming version of engauge, please see similar issue https://github.com/markummitchell/engauge6/issues/51 , I hope it would help.

In the meantime you could try this latest build from CI?
https://ci.appveyor.com/api/buildjobs/pxbt18jun1hvtgkl/artifacts/engauge-build.zip
If it still doesn't work with your locale, select the English/United States in Engauge Settings->MainWindow

**Comment by markummitchell** [comment]
Periods and commas are used differently according to locale.

**Comment by np-8** [comment]
The latest build (7.0) did not allow insertion of dot, either. After inserting commas, you cannot press 'Ok'. The 'e'-notation worked with 7.0.

There are some differences between the 6.2 and the 7.0

**In 6.2**: 1e-1 is converted into 0.1 after pressing Ok. (sometimes I got 1e-1 for some reason.. After restart it started to give 0.1 again)
**In 7.0**: 1e-1 is converted into 0,1 after pressing Ok.

**Comment by crayxt** [comment]
@np-8 Did setting the locale to English help?

**Comment by np-8** [comment]
@crayxt I have not yet tried changing the locale to English, since it would require reboot, which is right now not possible.

**Comment by crayxt** [comment]
I mean change the locale in Engauge settings, not in Windows

**Comment by np-8** [comment]
@crayxt I could not find locale settings in Engauge. Where should I find that?

**Comment by markummitchell** [comment]
I think Settings/MainWindow but I am not near a computer.

**Comment by markummitchell** [comment]
Settings/MainWindow brings up the locale setting. This is initially set to the system default, and is provided there so you can change it within Engauge without affecting the rest of your computer.

**Comment by np-8** [comment]
Settings/MainWindow? Oh, now I see. It is not in the Engauge 6.2, but only in Engauge 7.0.

Changing locale to 'English/United States' fixed it! Now It is possible to enter "0.2" etc., and the coordinates are calculated correcly.

**Comment by crayxt** [comment]
@np-8 You may want to close this ticket now. Thanks,
