### ISSUE TITLE
Question: Is the accuracy limited to 'pixels'?

### ISSUE THREAD

**Issue by np-8** [markummitchell/engauge6#80]
I found out [here](http://digitizer.sourceforge.net/usermanual/betteraccuracy.html) that " all points are only as accurate as the pixel size", and "It is not possible to define points that are 'between' pixels, even by zooming in closer.". 

However, I found out that you might actually put the markers to fractional coordinates, such as (2668.62, 1257.12) as below. I am now really getting this "better accuracy", or is this coordinate truncated into (2669, 1257) in calculations? Therefore, should I always pre-magnify my figures by scaling them to 200% or 400% of the original size (with GIMP or similar)? 

![coordinates](https://cloud.githubusercontent.com/assets/17479683/13347612/8f96e19e-dc77-11e5-8b29-d0259a263675.PNG)

**Comment by markummitchell** [comment]
Yes, the accuracy is limited to pixels. If you look at the Point coordinates in the DIG files, you'll see that they are integers. So, to get the best accuracy you can increase the zoom. 

The coordinates of the axis points are stored and processed as double precision numbers. They are never truncated into integers.
